import Head from 'next/head';
import Link from 'next/link';
import Image from 'next/image';
import { sanityClient, urlFor } from '../lib/sanity';

const developerQuery = `*[_type == 'developer']{
  _id,
  slug,
  name,
  about,
  image,
}`;

export default function Home({ developers }) {
  return (
    <div className='py-12 mb-12'>
      <Head>
        <title>HAK | Portfolio</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <div className='py-8 mx-auto sm:max-w-xl md:max-w-full lg:max-w-6xl lg:px-0 px-4 lg:py-12'>
        {developers?.length > 0 &&
          developers.map((developer) => (
            <div className='grid gap-10 lg:grid-cols-2' key={developer._id}>
              <div className='lg:pr-1'>
                <h5 className='mb-4 text-indigo-400 text-4xl font-extrabold leading-none'>
                  Yoo! I'm {developer.name} <br className='hidden sm:block' />
                  <span className='inline-block text-gray-100 text-3xl mt-4'>
                    Fullstack <br /> Web Developer
                  </span>
                </h5>
                <p className='mb-6 text-gray-300 text-2xl'>{developer.about}</p>
                <hr className='mb-5 border-gray-300' />
                <div className='grid grid-cols-2 w-1/2'>
                  <Link href='/contact' passHref={true}>
                    <button className='mr-2 items-center px-4 py-2 border border-gray-300 shadow-sm text-lg font-medium rounded-md text-gray-700 bg-white hover:bg-indigo-40 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500 text-center'>
                      Contact
                    </button>
                  </Link>
                  <Link href='/projects' passHref={true}>
                    <button className='mr-2 items-center px-4 py-2 border border-gray-300 shadow-sm text-lg font-medium rounded text-gray-700 bg-white hover:bg-indigo-40 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500 text-center'>
                      Projects
                    </button>
                  </Link>
                </div>
              </div>
              <div className='w-full rounded shadow-lg overflow-hidden'>
                <Image
                  layout='responsive'
                  width='100'
                  height='60'
                  src={urlFor(developer.image).url()}
                  className='rounded w-full object-cover object-center mb-6'
                />
              </div>
            </div>
          ))}
      </div>
    </div>
  );
}

export async function getStaticProps() {
  const developers = await sanityClient.fetch(developerQuery);
  return {
    props: {
      developers,
    },
  };
}


